### PR TITLE
Algorithm fixups

### LINKED ISSUE #13068: 🐞 Bug crew-mvdir error
```
shaderc: Collection of tools, libraries and tests for shader compilation
Precompiled binary available, downloading...
Shaderc archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install for shaderc...
Performing install for shaderc...
Using rdfind to convert duplicate files to hard links.
Now scanning ".", found 81 files.
Now have 81 files in total.
Removed 0 files due to nonunique device and inode.
Total size is 177304909 bytes or 169 MiB
Removed 73 files due to unique sizes from list. 8 files left.
Now eliminating candidates based on first bytes: removed 0 files from list. 8 files left.
Now eliminating candidates based on last bytes: removed 3 files from list. 5 files left.
Now eliminating candidates based on sha1 checksum: removed 5 files from list. 0 files left.
It seems like you have 0 files that are not unique
Totally, 0 B can be reduced.
Now making hard links.
Making 0 links.
Running upx to uncompress binaries if needed.
/usr/local/lib64/libSPVRemapper.so: symlink() failed: File exists
src is ./usr/local
dst is /usr/local/
total 208
drwxr-xr-x 1 chronos chronos  4096 Jul 21 18:49 ./
drwxr-xr-x 1 root    root     4096 May 14  2021 ../
drwxr-xr-x 1 chronos chronos  4096 Oct  6 02:29 .cache/
drwxr-xr-x 1 chronos chronos  4096 Oct  6 02:29 .config/
drwxr-xr-x 1 chronos chronos 20480 Oct  6 02:59 bin/
drwxr-xr-x 1 chronos chronos  4096 Jul 21 18:49 cache/
drwxr-xr-x 2 chronos chronos  4096 Oct  5 09:56 doc/
drwxr-xr-x 2 chronos chronos  4096 Oct  5 09:56 docbook/
drwxr-xr-x 1 chronos chronos  4096 Oct  6 02:28 etc/
drwxr-xr-x 1 chronos chronos 12288 Oct  6 02:59 include/
drwxr-xr-x 1 chronos chronos  4096 Oct  6 02:28 lib/
drwxr-xr-x 1 chronos chronos 73728 Oct  6 03:00 lib64/
drwxr-xr-x 1 chronos chronos  4096 Oct  6 02:28 libexec/
drwxr-xr-x 1 chronos chronos  4096 Oct  6 02:25 man/
drwxr-xr-x 1 chronos chronos  4096 Oct  6 02:28 sbin/
drwxr-xr-x 1 chronos chronos  4096 Oct  6 02:59 share/
drwxrwxrwt 1 chronos chronos  4096 Oct  6 02:59 tmp/
drwxr-xr-x 1 chronos chronos  4096 Oct  6 02:26 var/
crew-mvdir had an error. Using rsync.
```

### PR DESCRIPTION
**Pull request by supechicken**
Fixes https://github.com/chromebrew/chromebrew/issues/13068
Reverts #2 

## Changes
- Revert #2 to make things simpler
- Fix remove algorithm for symlinks
- Fix copying-deleting fallback logic when `rename()` does not work
- Also made some code refactoring

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
-  Copyright (C) 2013-2024 Chromebrew Authors
+  Copyright (C) 2013-2025 Chromebrew Authors
```
Comment (uberhacker) [inline src/main.c:2]: Should this file also have a version to track changes?

Comment (supechicken) [reply src/main.c:2]: Added a line for the version

**Review by satmandu — COMMENTED** [review]
Can you add a no op `--version` option that just dumps the version so we can test to see if the app segfaults?

**Comment by supechicken** [comment]
> Can you add a no op `--version` option that just dumps the version so we can test to see if the app segfaults?

Already added 👍

**Review by satmandu — COMMENTED** [review]
Also less urgently, it would be useful to have a Makefile and man page, so we can just make this a model app for our packages.

**Comment by satmandu** [comment]
> > Can you add a no op `--version` option that just dumps the version so we can test to see if the app segfaults?
> 
> Already added 👍

Please add that to the Readme!

**Comment by satmandu** [comment]
Please tag a release!

**Comment by supechicken** [comment]
@satmandu I have added a makefile in the latest commit
